# Generated by Django 6.0.4 on 2026-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Road', 'রাস্তা বা গর্ত'), ('Waste', 'ময়লা-আবর্জনা'), ('Electricity', 'বিদ্যুৎ বা ল্যাম্পপোস্ট'), ('Water', 'পানি বা ড্রেনেজ')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='incidents/')),
                ('severity', models.CharField(choices=[('Low', 'কম গুরুত্ব'), ('Medium', 'মাঝারি'), ('High', 'অত্যধিক জরুরি')], default='Medium', max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
