# Generated by Django 5.1.2 on 2026-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_incident_author_alter_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
