# Generated by Django 5.1.2 on 2026-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Road or Hole', 'Road or Hole'), ('Waste or Garbage', 'Waste or Garbage'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
